org: deskevinmendez
app: my-medium-proxy
service: fastify-proxy
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20200924

functions:
  proxy:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
          cors: true
