name: deploy-to-lambda
on: [push]
jobs:
  deploy_source:
    name: deploy medium proxy
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Install dependencies
        env:
          CI: true
        run: |
          npm install -g yarn serverless
          npm install
      - name: Login into AWS
        run: |
          serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy lambda
        run: sls deploy

