name: deploy-to-lambda
on: [push]
jobs:
  deploy_source:
    name: deploy medium proxy
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          npm install -g yarn serverless
          npm install
      - name: Login into AWS and deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          serverless deploy

